from summary.connector import DBConnection
from summary import engine
from summary.models import Role, User, Comment, News


front_roles_form_data = [
    {"id": 1, "name": 'admin'},
    {"id": 2, "name": 'moderator'},
    {"id": 3, "name": 'author'}
]

with DBConnection(engine=engine) as session:
    for obj in front_roles_form_data:
        session.add(Role(**obj))

    session.commit()

front_users_form_data = [
    {"id": 1, "first_name": 'Stephanie', "last_name": 'Bowman', "phone": '774 838-03-49', "email": 'bowman.s@gmail.com',
     "password": 'j%Q9VYcT$m', "repeat_password": 'j%Q9VYcT$m', "role_id": 1, "rating": 0, "deleted": False,
     "created_at": '2023-10-20 06:26:20'},
    {"id": 2, "first_name": 'Elizabeth', "last_name": 'Hebert', "phone": '349 217-71-87', "email": 'imiller@gmail.com',
     "password": '#7YN9dKwoW', "repeat_password": '#7YN9dKwoW', "role_id": 3, "rating": 4, "deleted": False,
     "created_at": '2020-09-13 00:55:33'},
    {"id": 3, "first_name": 'William', "last_name": 'Murphy', "phone": '+7 973 206-49-20',
     "email": 'murphywilliams@gmail.com', "password": ')3QWrItLiO', "repeat_password": ')3QWrItLiO', "role_id": 3,
     "rating": 3, "deleted": False, "created_at": '2021-08-18 05:25:18'},
    {"id": 4, "first_name": 'Richard', "last_name": 'Randolph', "phone": '577-545-312-29',
     "email": 'rich.randolph87@yahoo.com', "password": '(0XZmm(mUP', "repeat_password": '(0XZmm(mUP', "role_id": 2,
     "rating": 0, "deleted": False, "created_at": '2022-08-17 08:29:53'},
    {"id": 5, "first_name": 'Connor', "last_name": 'Wright', "phone": '310-354-9477', "email": 'c.wright05@icloud.com',
     "password": 'FgQ9oHtWW!', "repeat_password": 'FgQ9oHtWW!', "role_id": 2, "rating": 0, "deleted": False,
     "created_at": '2022-05-09 05:30:04'},
    {"id": 6, "first_name": 'Robert', "last_name": 'Moore', "phone": '+1-757-645-12-12', "email": 'r.moore98@gmail.com',
     "password": '62aZrOJD!a', "repeat_password": '62aZrOJD!a', "role_id": 3, "rating": 2, "deleted": False,
     "created_at": '2020-04-16 18:53:14'},
    {"id": 7, "first_name": 'Julie', "last_name": 'Barker', "phone": '7547137387', "email": 'juliebarker@gmail.com',
     "password": 'F_3*JMwaRV', "repeat_password": 'F_3*JMwaRV', "role_id": 3, "rating": 3, "deleted": False,
     "created_at": '2021-02-10 21:31:23'},
    {"id": 8, "first_name": 'Michele', "last_name": 'Santos', "phone": '+(514)979-777-10',
     "email": 'mich.shele78@gmail.com', "password": 'JB5_DaVF+5', "repeat_password": 'JB5_DaVF+5', "role_id": 3,
     "rating": 7, "deleted": False, "created_at": '2022-06-22 22:21:40'},
    {"id": 9, "first_name": 'Vanessa', "last_name": 'James', "phone": '+1-783-501-525', "email": 'vanessa92@icloud.com',
     "password": '$z8P3AHbd1', "repeat_password": '$z8P3AHbd1', "role_id": 3, "rating": 1, "deleted": False,
     "created_at": '2021-02-23 23:54:03'},
    {"id": 10, "first_name": 'Anna', "last_name": 'Hall', "phone": '(961)123-3341', "email": 'a.hall@yahoo.com',
     "password": 'Z67JrxaF(R', "repeat_password": 'Z67JrxaF(R', "role_id": 3, "rating": 8, "deleted": False,
     "created_at": '2020-03-21 21:57:01'},
    {"id": 11, "first_name": 'Jesus', "last_name": 'Michael', "phone": '001-769-190', "email": 'jes.mich@gmail.com',
     "password": 'nBK!3VAd@#', "repeat_password": 'nBK!3VAd@#', "role_id": 3, "rating": 8, "deleted": False,
     "created_at": '2022-03-19 15:43:11'},
    {"id": 12, "first_name": 'Angela', "last_name": 'Rodriguez', "phone": '671 584-69-98',
     "email": 'ang.rodriguez@gmail.com', "password": '^70HRg4a*j', "repeat_password": '^70HRg4a*j', "role_id": 3,
     "rating": 9, "deleted": False, "created_at": '2022-04-15 02:19:18'},
    {"id": 13, "first_name": 'Whitney', "last_name": 'Mcneil', "phone": '950 611-87-26',
     "email": 'whitney.mc83@gmail.com', "password": '4osy0Sph+n', "repeat_password": '4osy0Sph+n', "role_id": 3,
     "rating": 4, "deleted": False, "created_at": '2023-09-25 03:32:25'},
    {"id": 14, "first_name": 'Brenda', "last_name": 'Walter', "phone": '715 359-63-93',
     "email": 'br.endawalt@yahoo.com', "password": 'u&5I$ZvLrD', "repeat_password": 'u&5I$ZvLrD', "role_id": 3,
     "rating": 8, "deleted": False, "created_at": '2023-09-25 03:05:46'},
    {"id": 15, "first_name": 'Christopher', "last_name": 'Wells', "phone": '740 396-53-71', "email": 'sevans@gmail.com',
     "password": '(2&EZqlKO(', "repeat_password": '(2&EZqlKO(', "role_id": 3, "rating": 8, "deleted": False,
     "created_at": '2022-02-11 19:35:00'},
    {"id": 16, "first_name": 'David', "last_name": 'Lynch', "phone": '+1 696 009-34-74', "email": 'uthompson@yahoo.com',
     "password": 'ii08vEpNl+', "repeat_password": 'ii08vEpNl+', "role_id": 3, "rating": 4, "deleted": False,
     "created_at": '2023-08-17 11:48:04'},
    {"id": 17, "first_name": 'Christopher', "last_name": 'Daniels', "phone": '388 979-66-24',
     "email": 'gbates@icloud.com', "password": '5eYMuSpV*G', "repeat_password": '5eYMuSpV*G', "role_id": 3, "rating": 3,
     "deleted": False, "created_at": '2022-04-30 19:13:31'},
    {"id": 18, "first_name": 'Jared', "last_name": 'White', "phone": '121 676-00-62',
     "email": 'jared97.white@yahoo.com', "password": '+$we67NymB', "repeat_password": '+$we67NymB', "role_id": 3,
     "rating": 7, "deleted": False, "created_at": '2020-10-22 08:29:51'},
    {"id": 19, "first_name": 'Ashley', "last_name": 'Washington', "phone": '+13 455-81-47', "email": 'xevans@yahoo.com',
     "password": ')6RGBn9h@7', "repeat_password": ')6RGBn9h@7', "role_id": 3, "rating": 5, "deleted": False,
     "created_at": '2022-09-30 20:20:36'},
    {"id": 20, "first_name": 'Clinton', "last_name": 'Cochran', "phone": '+001 771-79-60', "email": 'radams@gmail.com',
     "password": '@Ir2FeLsw&', "repeat_password": '@Ir2FeLsw&', "role_id": 3, "rating": 7, "deleted": False,
     "created_at": '2021-05-05 12:06:42'},
    {"id": 21, "first_name": 'Stephanie', "last_name": 'Wong', "phone": '780 464-31-88',
     "email": 'michele91@icloud.com', "password": 'b_6ZSEsvwQ', "repeat_password": 'b_6ZSEsvwQ', "role_id": 3,
     "rating": 2, "deleted": False, "created_at": '2021-07-24 22:12:34'},
    {"id": 22, "first_name": 'Jacqueline', "last_name": 'Perkins', "phone": '+425 350-11-29',
     "email": 'voneal@yahoo.com', "password": 'pzR0QxDD!%', "repeat_password": 'pzR0QxDD!%', "role_id": 3, "rating": 8,
     "deleted": False, "created_at": '2021-06-13 15:23:44'},
    {"id": 23, "first_name": 'Ronald', "last_name": 'Howard', "phone": '694 624-24-73',
     "email": 'candicecollins@icloud.com', "password": '(bzSTNpNa5', "repeat_password": '(bzSTNpNa5', "role_id": 3,
     "rating": 8, "deleted": False, "created_at": '2021-11-06 04:44:16'},
    {"id": 24, "first_name": 'Kaitlin', "last_name": 'Downs', "phone": '+001 844-79-52', "email": 'tammy54@yahoo.com',
     "password": '&%RUQk4mXJ', "repeat_password": '&%RUQk4mXJ', "role_id": 2, "rating": 0, "deleted": False,
     "created_at": '2021-12-23 08:13:56'},
    {"id": 25, "first_name": 'Robert', "last_name": 'Miller', "phone": '+1 284-107-020', "email": 'qhayes@gmail.com',
     "password": 'ZvovI*yS*9', "repeat_password": 'ZvovI*yS*9', "role_id": 2, "rating": 0, "deleted": False,
     "created_at": '2020-04-25 01:16:09'}
]

with DBConnection(engine=engine) as session:
    for obj in front_users_form_data:
        session.add(User(**obj))

    session.commit()

front_news_form_data = [
    {"id": 1, "title": 'Debate picture stop interesting weight.',
     "content": 'Prepare measure every play western realize. Poor do herself head.', "author_id": 20,
     "moderated": False, "deleted": False, "created_at": '2021-04-03 02:26:36'},
    {"id": 2, "title": 'Name project she response size face measure.',
     "content": 'Push term industry glass. Husband natural while goal one training follow. Store what especially drive crime. Later heart price little skin score contain.',
     "author_id": 20, "moderated": True, "deleted": False, "created_at": '2023-08-19 20:02:15'},
    {"id": 3, "title": 'Manager article customer write involve this.',
     "content": 'Age still defense history. Large boy free finish above base onto. Grow seek marriage six sport none Congress. Either move meet everybody piece great or with. Occur song school third popular.',
     "author_id": 6, "moderated": False, "deleted": False, "created_at": '2023-08-23 07:16:02'},
    {"id": 4, "title": 'Federal Democrat read any scene third protect.',
     "content": 'And five particularly red someone seek focus expert. Drive tonight hair play. Ability space research movement move.',
     "author_id": 11, "moderated": False, "deleted": False, "created_at": '2020-06-19 07:25:49'},
    {"id": 5, "title": 'Them smile able whether challenge.',
     "content": 'Too writer son receive training again remain nearly. While wrong base choice live serve center physical.',
     "author_id": 11, "moderated": False, "deleted": False, "created_at": '2023-05-16 09:36:02'},
    {"id": 6, "title": 'Attorney different employee need.',
     "content": 'Particular end test affect difficult or. Soon security half loss move. Action suddenly upon imagine so free adult. Believe finish box play. Right chance interesting world decade analysis film appear.',
     "author_id": 14, "moderated": True, "deleted": False, "created_at": '2020-05-15 13:41:40'},
    {"id": 7, "title": 'Agree value page effort.',
     "content": 'Whole late within piece weight particularly social agreement. Then arrive camera forget. Together hotel its into computer. Any much floor message pretty trip month.',
     "author_id": 16, "moderated": False, "deleted": False, "created_at": '2023-08-26 02:19:20'},
    {"id": 8, "title": 'Detail modern approach teacher.',
     "content": 'Better window her case. Chair business off sit cost. Yeah attention forget. Gun everyone positive prove heavy strong. Cell lay top scientist process red hospital often. Art agency traditional along.',
     "author_id": 9, "moderated": False, "deleted": False, "created_at": '2020-05-19 07:48:49'},
    {"id": 9, "title": 'Court ok value large individual.',
     "content": 'Try hotel up walk. None other defense people after career. Maybe himself cup consumer what believe office.',
     "author_id": 8, "moderated": False, "deleted": False, "created_at": '2023-04-29 11:52:08'},
    {"id": 10, "title": 'There including face.',
     "content": 'Show cost treat keep. World sing decade truth. Minute eight talk consider response reduce. List actually worry benefit participant. It collection today answer.',
     "author_id": 18, "moderated": True, "deleted": False, "created_at": '2023-09-25 20:40:00'},
    {"id": 11, "title": 'Outside argue view teacher study.',
     "content": 'Truth thus attack save participant dog wish. During customer both box product. Little how look pick simple actually easy. Bill mean low spend themselves night wind outside.',
     "author_id": 20, "moderated": True, "deleted": False, "created_at": '2022-07-24 04:24:06'},
    {"id": 12, "title": 'Bar growth report increase.',
     "content": 'Could attention include leader movie. Such remember threat. Against itself new. Community happen region support our side.',
     "author_id": 2, "moderated": False, "deleted": False, "created_at": '2020-02-10 04:45:18'},
    {"id": 13, "title": 'Part read good control young financial attention.',
     "content": 'Them country give sport unit beyond. Pass especially give everyone upon. Good about source fight play despite word. Soldier note what there skill land. Truth ground describe only consider believe.',
     "author_id": 2, "moderated": True, "deleted": False, "created_at": '2023-03-11 09:41:40'},
    {"id": 14, "title": 'Character cover yard really fact drop.',
     "content": 'Today rise need college level those. Soldier federal prevent speak. Cut exist state improve. Picture service rule participant understand. Artist up ball ahead short save wish reveal.',
     "author_id": 21, "moderated": False, "deleted": False, "created_at": '2023-11-05 19:39:15'},
    {"id": 15, "title": 'Figure economic particularly lead particularly.',
     "content": 'Threat full suddenly area bring also go on. Best purpose one attack computer describe. Hour protect form win fill.',
     "author_id": 2, "moderated": False, "deleted": False, "created_at": '2022-04-15 22:02:57'},
    {"id": 16, "title": 'Outside enjoy result suffer five.',
     "content": 'Protect apply include meeting what. Trial test begin if industry. Type crime yourself big. Attorney organization some. Wide black reflect capital police.',
     "author_id": 19, "moderated": True, "deleted": False, "created_at": '2023-02-26 06:10:50'},
    {"id": 17, "title": 'Civil religious increase environment to laugh.',
     "content": 'Ago when receive student. Eye lawyer small threat. Authority paper let several attack. Would minute herself sense. Key north family reflect significant help produce. Foot nor firm senior buy while.',
     "author_id": 18, "moderated": True, "deleted": False, "created_at": '2023-09-14 12:39:13'},
    {"id": 18, "title": 'Travel time image most personal blood degree.',
     "content": 'Necessary create travel ability wish. At happen color medical street. Pay personal truth kid result safe half.',
     "author_id": 11, "moderated": True, "deleted": False, "created_at": '2022-12-07 23:41:22'},
    {"id": 19, "title": 'Ok price their candidate than environmental student modern.',
     "content": 'Live add drop return dark time you. Actually social contain forward candidate. Run strategy choice team. Leave political thank six attention hope interesting. Kid nature order something subject dog.',
     "author_id": 3, "moderated": False, "deleted": False, "created_at": '2021-08-31 06:06:45'},
    {"id": 20, "title": 'Score shake company window another important serious.',
     "content": 'Become training part take visit perhaps board. Clear later Congress environment. Part test these TV. Kind seven soldier expect mind. Help sell task include. Family look same stand office experience.',
     "author_id": 8, "moderated": False, "deleted": False, "created_at": '2021-02-13 00:55:59'},
    {"id": 21, "title": 'Fly fund sister image develop.',
     "content": 'Bar Mr shoulder focus stage member. Character expert argue at chair wrong base. Help themselves tough explain. Buy operation bit. Trial tell feeling once red then.',
     "author_id": 21, "moderated": True, "deleted": False, "created_at": '2023-08-09 17:45:00'},
    {"id": 22, "title": 'Parent section begin become brother sit hear.',
     "content": 'Son character join serve. Account reduce determine occur bill. Instead painting data structure. Science wait both including best another result. Win ready yes admit.',
     "author_id": 2, "moderated": False, "deleted": False, "created_at": '2020-02-20 12:20:41'},
    {"id": 23, "title": 'Six learn red night treatment inside.',
     "content": 'Far quality suggest heart base difficult. Course media structure family country one. Claim describe couple government ever allow hard.',
     "author_id": 8, "moderated": False, "deleted": False, "created_at": '2022-07-30 12:49:52'},
    {"id": 24, "title": 'Which group threat so son dinner child free.',
     "content": 'Several writer general interview then collection. At past actually imagine throughout structure situation country. Create really two eye behind thank.',
     "author_id": 6, "moderated": False, "deleted": False, "created_at": '2020-11-13 23:41:03'},
    {"id": 25, "title": 'My prevent that bill.',
     "content": 'Appear debate skin choose forward finally. As member red economy Mrs. Have produce ask. Politics already mother particularly cold. Film involve wall ground win involve.',
     "author_id": 11, "moderated": False, "deleted": False, "created_at": '2021-12-15 13:06:25'},
    {"id": 26, "title": 'Quite drop keep race police player home.',
     "content": 'Region offer scientist art major return different. Interesting out approach side lawyer issue cell.',
     "author_id": 13, "moderated": True, "deleted": False, "created_at": '2020-07-14 05:14:29'},
    {"id": 27, "title": 'Theory offer environmental those.',
     "content": 'Range road music marriage. Front anyone child service time buy movie nothing. Data outside material. Say rich list three realize. Education party democratic offer.',
     "author_id": 18, "moderated": True, "deleted": False, "created_at": '2020-05-25 04:57:51'},
    {"id": 28, "title": 'Avoid should teach think everybody discover.',
     "content": 'Share behind issue able letter election sister. Compare let but why professor after song six. Trouble science job newspaper bit. Skin color against well on yes thought. Lay charge discussion game.',
     "author_id": 11, "moderated": False, "deleted": False, "created_at": '2021-11-23 09:38:44'},
    {"id": 29, "title": 'Team start team member risk.',
     "content": 'Listen ask property toward home. Tough beautiful information fast. Address service visit reduce lawyer. Drug poor oil although. Among heart paper drug tough nothing you.',
     "author_id": 23, "moderated": True, "deleted": False, "created_at": '2022-09-22 13:13:41'},
    {"id": 30, "title": 'Line produce most.',
     "content": 'Stop rich too despite. Recently there since have. Dream easy language issue which better affect. Stop gun two face tell when tree.',
     "author_id": 10, "moderated": False, "deleted": False, "created_at": '2021-09-24 05:39:39'},
    {"id": 31, "title": 'Camera gun however.',
     "content": 'Window painting cause partner majority light draw. Available return team visit firm responsibility. Tv practice size. Also bad her base rock.',
     "author_id": 22, "moderated": True, "deleted": False, "created_at": '2022-04-03 04:06:29'},
    {"id": 32, "title": 'Worker term star reflect stage benefit feel section.',
     "content": 'Lay suddenly dark work population charge should. Program enjoy worry fear offer. Different share sound need so almost support.',
     "author_id": 22, "moderated": True, "deleted": False, "created_at": '2020-05-28 23:35:42'},
    {"id": 33, "title": 'Hospital spring drug sound mind whatever.',
     "content": 'Suddenly hundred service modern sort win I. Local military two should idea everyone during. May style him dream. Thank quality prepare arrive.',
     "author_id": 20, "moderated": True, "deleted": False, "created_at": '2022-05-29 21:22:16'},
    {"id": 34, "title": 'Two follow man why.',
     "content": 'East treat cultural generation art official material house. Training establish sit return. War program set stop attorney try.',
     "author_id": 7, "moderated": True, "deleted": False, "created_at": '2020-08-22 02:11:54'},
    {"id": 35, "title": 'Training near possible surface if.',
     "content": 'Town assume return school even find. If reduce president remain local. Month institution high. Budget science determine. Face store human fall dinner start. Enter alone open air before.',
     "author_id": 23, "moderated": True, "deleted": False, "created_at": '2022-09-18 23:27:47'},
    {"id": 36, "title": 'Glass buy soldier movie realize level spend her.',
     "content": 'Over recently control station. Company sometimes turn sell. Down should story each industry produce.',
     "author_id": 20, "moderated": False, "deleted": False, "created_at": '2022-07-24 01:46:16'},
    {"id": 37, "title": 'Sit can hundred suffer against easy shake.',
     "content": 'Myself property wear property care. Year man subject admit community. Class teach author thing what involve. Name community hotel develop left.',
     "author_id": 7, "moderated": False, "deleted": False, "created_at": '2021-12-14 02:16:15'},
    {"id": 38, "title": 'And safe wife hard whatever their news.',
     "content": 'Full likely than enter measure down. Scientist someone kind. Girl exactly trip toward lawyer benefit. Wind site near send hear art seat. Improve mind side sometimes themselves view.',
     "author_id": 18, "moderated": True, "deleted": False, "created_at": '2022-12-16 15:38:51'},
    {"id": 39, "title": 'Against table drop lawyer.',
     "content": 'Feeling stock while. Throw mind staff author. Relate exactly matter network. Quality tell career. Contain left necessary. Hit citizen official best.',
     "author_id": 16, "moderated": True, "deleted": False, "created_at": '2022-09-28 17:52:43'},
    {"id": 40, "title": 'Debate knowledge challenge range result cost skill.',
     "content": 'Current stop billion ago nice. Particularly office dinner save act quality child. Ok stop hotel fall weight century continue.',
     "author_id": 9, "moderated": False, "deleted": False, "created_at": '2022-12-08 03:15:36'}
]

with DBConnection(engine=engine) as session:
    for obj in front_news_form_data:
        session.add(News(**obj))

    session.commit()

front_comments_form_data = [
    {"id": 1,
     "content": 'Money but parent address strategy pattern. Onto respond space identify agent four. Trouble once market security couple plan. Authority maintain whom school effort.',
     "author_id": 13, "news_id": 22, "deleted": False, "created_at": '2022-03-27 04:35:14'},
    {"id": 2,
     "content": 'Car wear remember believe. Fund reduce life class. Individual especially red region fact teach drop. Where situation read. Among including four prevent check learn but age.',
     "author_id": 8, "news_id": 21, "deleted": False, "created_at": '2023-07-25 14:56:20'},
    {"id": 3,
     "content": 'Effort exist expect. Dark high keep sure least again change. Let myself day entire major increase.',
     "author_id": 20, "news_id": 6, "deleted": False, "created_at": '2020-12-16 15:32:08'},
    {"id": 4,
     "content": 'Inside beautiful yeah expect. Leg environment prevent how successful. Them collection place middle however human address. Month but idea lead enjoy live imagine. Also great human.',
     "author_id": 19, "news_id": 20, "deleted": False, "created_at": '2020-08-20 12:18:46'},
    {"id": 5,
     "content": 'Girl key human discover entire once action. World already offer report theory create. Receive minute itself pretty. Many heavy last blood.',
     "author_id": 22, "news_id": 14, "deleted": False, "created_at": '2020-12-05 17:10:21'},
    {"id": 6,
     "content": 'Example reality religious car close per. Option suffer appear run. Type area measure become. Sort form push real official. Performance show dinner drug.',
     "author_id": 7, "news_id": 10, "deleted": False, "created_at": '2023-03-02 07:25:46'},
    {"id": 7,
     "content": 'Movement painting section. Agreement performance democratic way. Clearly treatment herself bar fill child red art.',
     "author_id": 19, "news_id": 16, "deleted": False, "created_at": '2021-07-29 11:42:39'},
    {"id": 8,
     "content": 'Threat parent like. Big ever white deal dark price official none. Fish western large religious. Return thank program bank. Happy teach tough choice. His miss light pretty.',
     "author_id": 21, "news_id": 28, "deleted": False, "created_at": '2021-05-06 22:42:31'},
    {"id": 9,
     "content": 'Then property within authority miss quickly. Check boy almost back gun three sea. Body current even trade common. Four garden bed. Trial face near black down discover standard school.',
     "author_id": 11, "news_id": 38, "deleted": False, "created_at": '2020-05-04 12:38:16'},
    {"id": 10,
     "content": 'Else boy billion eat language site defense. Provide hand successful safe material today. Myself car strategy writer memory pass.',
     "author_id": 22, "news_id": 34, "deleted": False, "created_at": '2023-01-25 15:11:19'},
    {"id": 11,
     "content": 'Seat smile conference program true. According maybe tree answer. Political including outside what answer. Three seek official boy nation soon whether. Have concern would PM daughter face.',
     "author_id": 23, "news_id": 4, "deleted": False, "created_at": '2021-01-24 07:48:51'},
    {"id": 12,
     "content": 'Ever people senior phone lead. Make some country story possible. Back drive us trouble. Keep need need behind from black surface sit.',
     "author_id": 8, "news_id": 39, "deleted": False, "created_at": '2021-10-17 16:15:09'},
    {"id": 13,
     "content": 'Talk thus somebody property. Art account red prove. Economy book than four time. Debate focus I life. Beautiful feel central study public live song.',
     "author_id": 21, "news_id": 7, "deleted": False, "created_at": '2020-05-16 16:53:34'},
    {"id": 14,
     "content": 'Affect purpose town instead. Determine quickly speech ago first agree our. Here memory open those.',
     "author_id": 15, "news_id": 22, "deleted": False, "created_at": '2021-02-25 13:09:07'},
    {"id": 15,
     "content": 'Interview another end however dark again before. Still kind develop better. Some woman never effort. Possible vote about space today. Wife table suffer drive.',
     "author_id": 22, "news_id": 22, "deleted": False, "created_at": '2020-06-07 17:15:35'},
    {"id": 16,
     "content": 'Seat claim almost natural past need. Off over against computer easy. Take off campaign any administration assume near. Wait over campaign miss race should animal.',
     "author_id": 21, "news_id": 34, "deleted": False, "created_at": '2023-07-17 13:55:00'},
    {"id": 17,
     "content": 'Fall one environmental know fund. Political west president. Our wind sit fly collection a too three. Actually nation center charge.',
     "author_id": 12, "news_id": 32, "deleted": False, "created_at": '2022-11-22 08:19:03'},
    {"id": 18,
     "content": 'Central these anyone end. Star necessary off situation his good adult. Would career every travel ahead. Likely choice move success difficult ok. Crime bring rate technology drive.',
     "author_id": 19, "news_id": 35, "deleted": False, "created_at": '2020-10-11 11:57:50'},
    {"id": 19,
     "content": 'Impact kid ago sign son spring. Stand city upon democratic majority truth. Standard discuss second remain race life. Movement difficult increase lose boy.',
     "author_id": 19, "news_id": 9, "deleted": False, "created_at": '2022-03-25 16:12:20'},
    {"id": 20,
     "content": 'Me nearly number account religious just. Better region full. Itself present music half realize simply. Game page leader nearly.',
     "author_id": 12, "news_id": 8, "deleted": False, "created_at": '2022-06-18 01:50:39'},
    {"id": 21,
     "content": 'Girl community she commercial outside. Method describe wish ball there. Heart woman movie into religious southern consumer concern.',
     "author_id": 14, "news_id": 18, "deleted": False, "created_at": '2021-08-19 13:07:04'},
    {"id": 22,
     "content": 'Human own party people how modern capital. Its likely trip Republican analysis interesting. Away when establish reason human bit couple mouth. Candidate look nothing per follow follow house letter.',
     "author_id": 14, "news_id": 1, "deleted": False, "created_at": '2023-03-16 11:48:12'},
    {"id": 23,
     "content": 'Possible across tree. Should teacher policy through act. Church school free through low hard give. Look walk card leave relate able.',
     "author_id": 10, "news_id": 39, "deleted": False, "created_at": '2020-03-29 16:58:48'},
    {"id": 24,
     "content": 'Boy break compare discuss too building. Tonight remember doctor responsibility world. Begin say book suggest mean himself realize.',
     "author_id": 6, "news_id": 15, "deleted": False, "created_at": '2023-07-24 06:59:15'},
    {"id": 25,
     "content": 'Ever third from it front between type. Happen nothing word financial team win century. Movement off media order reduce glass.',
     "author_id": 20, "news_id": 23, "deleted": False, "created_at": '2020-01-16 03:32:52'},
    {"id": 26,
     "content": 'Bad drug expect us. Region season approach decision. Painting small too fall. Style long middle. She goal area customer government. Big task power politics box deep.',
     "author_id": 7, "news_id": 18, "deleted": False, "created_at": '2021-02-04 00:48:30'},
    {"id": 27,
     "content": 'Continue year interest amount through lose. Interview outside phone choose I discover including. Quite baby itself population.',
     "author_id": 6, "news_id": 14, "deleted": False, "created_at": '2021-10-20 06:06:32'},
    {"id": 28,
     "content": 'Force similar audience bit center amount. Page available present notice support. Education hit popular down offer.',
     "author_id": 3, "news_id": 19, "deleted": False, "created_at": '2021-04-07 07:47:40'},
    {"id": 29,
     "content": 'Million successful front conference day international economic. Station matter yes attack actually buy. Meet more under single. Attack since trip image spring wrong.',
     "author_id": 2, "news_id": 8, "deleted": False, "created_at": '2022-05-22 11:35:56'},
    {"id": 30,
     "content": 'Leave make indicate commercial. Debate month reflect ready moment. Bad assume major sign great candidate reality. Project big follow special card. Heavy however cold spring happen whatever.',
     "author_id": 12, "news_id": 1, "deleted": False, "created_at": '2021-01-22 06:37:00'},
    {"id": 31,
     "content": 'Free large time series cell own. Partner always rule different wall card generation. Compare stock expert window.',
     "author_id": 17, "news_id": 23, "deleted": False, "created_at": '2020-12-02 03:02:49'},
    {"id": 32,
     "content": 'Main little popular president be experience moment image. Suddenly moment short recognize trade finally. Challenge race possible bit usually various bill talk.',
     "author_id": 18, "news_id": 9, "deleted": False, "created_at": '2020-07-31 16:13:51'},
    {"id": 33,
     "content": 'Single case protect call above follow issue show. Wish player goal land day late mean growth. Parent set of action provide.',
     "author_id": 13, "news_id": 29, "deleted": False, "created_at": '2020-09-19 12:19:31'},
    {"id": 34,
     "content": 'Child federal tell marriage media effort. Event wonder general call. Position beautiful deep treatment specific authority. Here adult next successful although. Book these campaign three.',
     "author_id": 11, "news_id": 29, "deleted": False, "created_at": '2020-08-28 11:42:06'},
    {"id": 35,
     "content": 'Never once arm study. Every during never personal toward marriage. View sea different certainly their line. Significant store drug. All customer side. Response strong these.',
     "author_id": 2, "news_id": 28, "deleted": False, "created_at": '2023-07-20 09:28:35'},
    {"id": 36,
     "content": 'Education its mention above would. That eight color laugh option. Include attack improve with four.',
     "author_id": 7, "news_id": 26, "deleted": False, "created_at": '2021-08-05 12:06:06'},
    {"id": 37,
     "content": 'Have sister at expect computer small. These Mrs specific mission. Doctor significant author agree white. Can full stock stand huge.',
     "author_id": 13, "news_id": 16, "deleted": False, "created_at": '2021-01-21 15:48:49'},
    {"id": 38,
     "content": 'So prevent get difficult develop. Room share walk employee seven recent. Trip wall thought nation. Point direction decade special. Story though college with power research walk from.',
     "author_id": 2, "news_id": 39, "deleted": False, "created_at": '2020-03-17 20:08:13'},
    {"id": 39,
     "content": 'Set direction happy we choice ground be summer. Policy on respond current play fire model. Poor start identify. Blood I firm. Standard central in over quite growth where.',
     "author_id": 7, "news_id": 37, "deleted": False, "created_at": '2022-05-04 23:00:25'},
    {"id": 40,
     "content": 'Admit east point traditional. Get democratic action hot ahead war when. Total expect firm night. Piece wife personal win.',
     "author_id": 22, "news_id": 23, "deleted": False, "created_at": '2020-11-13 21:18:47'},
    {"id": 41,
     "content": 'War behind business investment. Camera simple yourself learn school military either. Every out so executive turn. Arm skill director these hot change bar. Value edge wish.',
     "author_id": 20, "news_id": 1, "deleted": False, "created_at": '2022-09-23 23:53:06'},
    {"id": 42,
     "content": 'Challenge later federal compare sense. Answer chair ahead. Land reflect east citizen common.',
     "author_id": 8, "news_id": 34, "deleted": False, "created_at": '2021-02-14 05:25:56'},
    {"id": 43,
     "content": 'Sing establish world experience. Time total lawyer lose prepare. Rather employee business those. Up age find son. Hard safe during. Partner use develop. Let station rest guess.',
     "author_id": 15, "news_id": 37, "deleted": False, "created_at": '2020-02-06 02:34:38'},
    {"id": 44,
     "content": 'Increase player a north term by third. Southern production anyone long gun. Over Democrat difference western prevent. Candidate cause probably speech.',
     "author_id": 22, "news_id": 21, "deleted": False, "created_at": '2023-03-08 08:38:43'},
    {"id": 45,
     "content": 'Bag believe produce almost subject. Sense contain few deal enter sell. Role politics recent strong west born.',
     "author_id": 13, "news_id": 27, "deleted": False, "created_at": '2023-01-31 00:20:10'},
    {"id": 46,
     "content": 'Positive need article sing seven they forget law. Understand until alone across carry describe. Traditional news mother card. Picture later office leader grow new. Food these general enjoy.',
     "author_id": 11, "news_id": 26, "deleted": False, "created_at": '2020-07-19 02:34:43'},
    {"id": 47,
     "content": 'Carry attorney north kid. Up professional see one entire soldier account. Everybody early thus but stock. Government age room determine.',
     "author_id": 16, "news_id": 2, "deleted": False, "created_at": '2020-10-11 09:13:27'},
    {"id": 48,
     "content": 'No after theory throughout present camera. Task bag trip various dog agency. Protect build mission writer. Decade issue social result finish moment expect. Central military ago plan best bar.',
     "author_id": 20, "news_id": 25, "deleted": False, "created_at": '2023-09-21 17:33:14'},
    {"id": 49,
     "content": 'Stuff produce six treat. Your quality plant provide must action culture. Probably hospital kid yard Mr election. Coach fine between enough. Paper understand special Mrs could good who third.',
     "author_id": 14, "news_id": 33, "deleted": False, "created_at": '2021-10-16 01:42:26'},
    {"id": 50,
     "content": 'Glass to scientist road. Tell add without evidence here teach you. Former appear administration assume week. Weight along successful rate school. Least set hand smile.',
     "author_id": 13, "news_id": 39, "deleted": False, "created_at": '2021-05-04 12:47:42'},
    {"id": 51,
     "content": 'Especially accept Congress method case base career. Town thing behind across. Range southern big find sense. Laugh rock customer degree. Event father project wrong. Opportunity cell then red.',
     "author_id": 10, "news_id": 6, "deleted": False, "created_at": '2020-02-26 13:34:01'},
    {"id": 52,
     "content": 'Detail much kid manage decide foot test. Former box citizen now yes. Back eye reason door really respond. Light decide night. Party plan cold determine.',
     "author_id": 20, "news_id": 9, "deleted": False, "created_at": '2021-04-25 21:50:11'},
    {"id": 53,
     "content": 'American suffer common treat reality produce. Force clearly there. Available week old great. Strong might feeling measure community arm should. Set myself study a attorney report on see.',
     "author_id": 19, "news_id": 39, "deleted": False, "created_at": '2022-03-06 23:24:16'},
    {"id": 54,
     "content": 'Individual film great research medical black all. Into police arrive. Consumer base they nothing budget magazine. Instead statement tree return sell.',
     "author_id": 13, "news_id": 12, "deleted": False, "created_at": '2023-05-18 05:48:01'},
    {"id": 55,
     "content": 'After show radio dark pick through. Rest eye page notice. Pretty TV fight when film. Finally speech north standard state. Tax large front teach. Clearly piece back continue.',
     "author_id": 9, "news_id": 30, "deleted": False, "created_at": '2023-02-18 17:13:20'},
    {"id": 56,
     "content": 'Can class begin institution. Section author eye cold either blue. Available enough notice simply crime. Rule before fight however. Treatment first thousand herself might no.',
     "author_id": 18, "news_id": 6, "deleted": False, "created_at": '2023-09-10 08:56:35'},
    {"id": 57,
     "content": 'Standard drug example hot. Growth water once vote surface black rise. History stage religious mention again well think.',
     "author_id": 15, "news_id": 21, "deleted": False, "created_at": '2022-03-19 23:33:27'},
    {"id": 58,
     "content": 'Ground space discussion. Whether nature beyond. Customer employee doctor quickly when across. Local think chance some catch very the. See important night decide pretty soon else.',
     "author_id": 14, "news_id": 39, "deleted": False, "created_at": '2021-04-10 06:10:10'},
    {"id": 59,
     "content": 'Item through much certainly budget. Message firm note itself soldier information. She second same must offer present.',
     "author_id": 12, "news_id": 1, "deleted": False, "created_at": '2020-12-15 19:43:44'},
    {"id": 60,
     "content": 'We your also as hair rock adult. Age officer day network end Mrs so. Part item reach none of oil over. Human forget lay Mr test. Employee method political.',
     "author_id": 13, "news_id": 21, "deleted": False, "created_at": '2020-11-25 05:17:24'},
    {"id": 61,
     "content": 'Really college several region anyone herself. Case detail would drug cold. Character similar difference interest another. If window enough deep easy rock. Debate officer social else.',
     "author_id": 2, "news_id": 27, "deleted": False, "created_at": '2023-03-29 04:55:42'},
    {"id": 62,
     "content": 'Night go listen other. Together simply apply body. Ten hand offer born big. Morning really international store rate hold.',
     "author_id": 15, "news_id": 22, "deleted": False, "created_at": '2020-09-18 14:45:34'},
    {"id": 63,
     "content": 'Say effect area just town. Owner arm standard generation. Reality child chair eye wear cold. People approach peace official how. Field brother structure kitchen top exist age.',
     "author_id": 17, "news_id": 17, "deleted": False, "created_at": '2022-01-18 01:34:03'},
    {"id": 64,
     "content": 'Him quickly cold establish example program. Poor word his free. Start piece face leader research old right.',
     "author_id": 12, "news_id": 10, "deleted": False, "created_at": '2020-04-15 21:53:01'},
    {"id": 65,
     "content": 'Half yeah onto. One choice reveal thing. Shoulder learn item professor above interesting rule. Hear leave list establish large clear town. Issue dream similar seem.',
     "author_id": 6, "news_id": 33, "deleted": False, "created_at": '2023-03-12 21:14:51'},
    {"id": 66,
     "content": 'Pretty both away close stay especially bed. Father southern ago half stock issue. Visit above term still card for list. Responsibility trade behind subject. True time over range.',
     "author_id": 22, "news_id": 23, "deleted": False, "created_at": '2020-12-10 04:48:01'},
    {"id": 67,
     "content": 'Outside such show society realize purpose. Director shake management meet issue reason his cultural. Born author address herself who.',
     "author_id": 20, "news_id": 20, "deleted": False, "created_at": '2020-03-17 16:21:58'},
    {"id": 68,
     "content": 'Pay between year arrive. Power base total change. Agency glass voice though mouth health. During part sit budget program.',
     "author_id": 17, "news_id": 21, "deleted": False, "created_at": '2022-07-29 21:27:57'},
    {"id": 69,
     "content": 'Ask would six glass more political. American nothing religious minute. Reflect approach them professor human course. Growth certain star way reality. Entire husband drop billion account woman.',
     "author_id": 7, "news_id": 9, "deleted": False, "created_at": '2021-05-11 03:17:30'},
    {"id": 70,
     "content": 'Brother possible dinner seven record person. How name it. Fall majority agency deep later. Along daughter already organization time according million will. Rich may bad at.',
     "author_id": 19, "news_id": 29, "deleted": False, "created_at": '2020-12-15 22:04:26'}
]

with DBConnection(engine=engine) as session:
    for obj in front_comments_form_data:
        session.add(Comment(**obj))

    session.commit()

    # comment = Comments(
    #     content="Test",
    #     author_id=1,
    #     news_id=2,
    #     deleted=False
    # )
    #
    # session.add(comment)

    # comments = [
    #     Comments(...),
    #     Comments(...),
    #     Comments(...),
    #     Comments(...),
    #     Comments(...),
    # ]
    #
    # session.create_all(comments)